// flow-typed signature: 3111399b5bbc4bdf2657825a680326a0
// flow-typed version: <<STUB>>/stringz_v0.4.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stringz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stringz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stringz/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'stringz/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'stringz/dist/index' {
  declare module.exports: any;
}

declare module 'stringz/dist/length' {
  declare module.exports: any;
}

declare module 'stringz/dist/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stringz/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'stringz/coverage/lcov-report/prettify'>;
}
declare module 'stringz/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'stringz/coverage/lcov-report/sorter'>;
}
declare module 'stringz/dist/index.js' {
  declare module.exports: $Exports<'stringz/dist/index'>;
}
declare module 'stringz/dist/length.js' {
  declare module.exports: $Exports<'stringz/dist/length'>;
}
declare module 'stringz/dist/string.js' {
  declare module.exports: $Exports<'stringz/dist/string'>;
}
